;koLibrary
;Графическая библиотека UI для KolibriOS

;include "koScreen.inc"
;include "koWindow.inc"
include "koString.inc"
include "koStyle.inc"
include "koObjectList.inc"
include "koView.inc"
include "koElementsView.inc"
include "koButton.inc"
;include "koImage.inc"
;include "koEdit.inc"
;include "koScrollBar.inc"
include "koTab.inc"
;include "koLabel.inc"
;include "koListBox.inc"
include "koProgressBar.inc"
;include "ko.inc"